### ISSUE TITLE
Hide Touch Bar upon computer start-up

### ISSUE THREAD

**Issue by matohop** [sindresorhus/touch-bar-simulator#65]
I tried going into Preferences -> Users & Groups -> Login Items and selected "Hide" to remedy this, but after restarting the computer, clicking on the Touch Bar icon in the status bar is unresponsive.

Am I doing something wrong? I would just like to have the application launch and stay "hidden" upon start-up.

**Comment by sindresorhus** [comment]
If it shows up in login items, it's because you manually added it before. You should remove it from there and use the "Launch At Login" checkbox in the app itself. Menu bar apps don't respond to the "Hide" checkbox anyway.

The proper solution is to detect whether the app was launched at login and not show the window then. For that, we need to implement https://github.com/sindresorhus/LaunchAtLogin/issues/33 first.

**Comment by m12386** [comment]
>Menu bar apps don't respond to the "Hide" checkbox anyway.

It worked in that the Touch Bar didn’t appear upon start-up, but like I said, clicking the menu bar icon wouldn’t show the Touch Bar. I’ve since removed it from Login Items and checked the Launch and Login checkbox like you recommended.

**Comment by sindresorhus** [comment]
Closing as this app is now discontinued.
